require "core.options"
require "core.plugins"

require "plugins.tokyonight"
require "plugins.autopairs"
require "plugins.treesitter"
require "plugins.impatient"
require "plugins.lualine"
require "plugins.nvimtree"
require "plugins.gitsigns"
require "plugins.wk"
require "plugins.bufferline"
require "plugins.bufdel"
require "plugins.colorizer"
require "plugins.blankline"
